/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    VerDescriptions: typeof import('@versakit/ui')['VerDescriptions']
    VerDescriptionsItem: typeof import('@versakit/ui')['VerDescriptionsItem']
    VerTag: typeof import('@versakit/ui')['VerTag']
  }
}
